name: go-build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: ./api/go.sum
        
    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build ./api/cmd/main.go

    - name: Test
      run: go test -v ./api/...
